services:

  # backend service
  backend:
    container_name: flask-student-api
    restart: always
    image: ${DOCKERHUB_USERNAME}/flask-student-api:v1.0
    build:
      context: ./backend
      dockerfile: flask.dockerfile
    ports:
      - 8080:8080
    env_file: ".env"
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@database:3306/${MYSQL_DATABASE}
      - PROMETHEUS_MULTIPROC_DIR=/tmp
    depends_on:
      - database


  # database service
  database:
    container_name: mysql-database
    image: mysql:5.7
    env_file: ".env"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
  

  # frontend service
  prometheus:
    container_name: prometheus
    image: prom/prometheus:main
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    container_name: grafana
    image: grafana/grafana:main-ubuntu
    ports:
      - "3000:3000"
    depends_on:
      - prometheus


volumes:
  mysql_data: {}



  

    
