
name: Build and Deploy to Dockerhub

on:
    push:
        branches:
            - master
        

jobs:
    backend-deploy:
        name: Build and deploy backend microservice
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code 
              uses: actions/checkout@v4

            - name: change directory
              run: cd backend

            - name: Build Docker image
              run: |
                docker build --file ./flask.dockerfile -t horlar/flask-student-api:v1.0 .

            - name: Docker Login (use secrets)
              run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${ secrets.DOCKERHUB_TOKEN }}

            - name: Docker Push
              run: |
                docker push horlar/flask-student-api:v1.0


