
name: Build and Deploy Flask API to DockerHub

on:
    push:
        branches:
            - master
        paths:
            - 'backend/**' # when a change is make to the backend
            - '.github/workflows/backend.yml' # when a change is made to the workflow

jobs:
    build-and-deploy:
        name: Build and deploy Docker Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code 
              uses: actions/checkout@v4


            - name: Build Flask Docker image
              run: |
                docker build --file backend/flask.dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-student-api:v1.0 backend

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Docker Push
              run: |
                docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-student-api:v1.0


