
# Workflow
name: Build and Deploy Flask API to DockerHub

# Trigger
on:
    workflow_dispatch:

    push:
        branches:
            - master
        paths:
            - 'backend/**' # when a change is make to the backend
            - '.github/workflows/backend.yml' # when a change is made to the workflow

jobs:
    build-and-deploy:
        name: Build and deploy Docker Image
        runs-on: aws-self-hosted

        steps:
            - name: Checkout code 
              uses: actions/checkout@v4


            - name: Build Flask Docker image
              run: |
                docker build --file backend/flask.dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-student-api:v1.0 backend

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Docker Push
              run: |
                docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-student-api:v1.0

    notify-success:
        name: Success Notification via Email
        runs-on: ubuntu-latest
        needs: build-and-deploy
        if: success() # only run if build-and-deploy job is successful
        steps:
            - name: Send successfull email notification
              uses: dawidd6/action-send-mail@v6
              with:
                server_address: smtp.gmail.com
                server_port: 465
                username: ${{ secrets.MAIL_USERNAME}}
                password: ${{ secrets.MAIL_PASSWORD }}
                subject: Flask Docker Deployment Successfull
                to: ${{ secrets.RECEIVER_EMAIL_ADDERESS }}
                from: ${{ secrets.SENDER_EMAIL_ADDERESS }}
                body: |
                   Dear team,
                   The Flask backend Docker Image has been built and deployed
                   successfully.

                   Repository Info:
                     - Repository: ${{ github.repository }}
                     - Branch: ${{ github.ref }}
                     - Commit: ${{ github.sha }}

                   Thank you!

    notify-fail:
        name: Fail Notification via Email
        runs-on: ubuntu-latest
        needs: build-and-deploy
        if: failure() # only run if build-and-deploy job is failed
        steps:
            - name: Send failed email notification
              uses: dawidd6/action-send-mail@v6
              with:
                server_address: smtp.gmail.com # smtp host
                server_port: 465 # smtp port
                username: ${{ secrets.MAIL_USERNAME }} # username
                password: ${{ secrets.MAIL_PASSWORD }} # password
                subject: Flask Docker Deployment Successfull
                to: ${{ secrets.RECEIVER_EMAIL_ADDERESS }}
                from: ${{ secrets.SENDER_EMAIL_ADDERESS }}
                body: |
                   Dear team,
                   The Flask backend Docker Image was not build
                   successfully.

                   Repository Info:
                     - Repository: ${{ github.repository }}
                     - Branch: ${{ github.ref }}
                     - Commit: ${{ github.sha }}

                   Thank you!

    run-docker-compose:
      name: Run docker compose
      runs-on: aws-self-hosted
      needs: notify-success
      steps:
        - name: Export all Environment Variable
          run: |
            export DOCKERHUB_USERNAME=${{ vars.DOCKERHUB_USERNAME }}
            export MYSQL_USER = ${{ vars.MYSQL_USER }}
            export MYSQL_PASSWORD = ${{ secrets.MYSQL_PASSWORD }}
            export MYSQL_DATABASE = ${{ vars.MYSQL_DATABASE }}
            export MYSQL_ROOT_PASSWORD = ${{ secrets.MYSQL_ROOT_PASSWORD }}
            export DATABASE_URL= mysql+pymysql://${{ vars.MYSQL_USER }}:${{ secrets.MYSQL_PASSWORD }}@database:3306/${{ vars.MYSQL_DATABASE }}
        - name: Run Docker Container
          run: docker-compose up -d
